type Query {
  currentDonations: String
  metrics: Metrics
}

type Mutation {
  signUp(name: String, email: String, betaTester: Boolean) : Result
  signupFellow(requestBody: FellowInput) : ID
  acceptFellowDonation(donation: FellowDonationInput) : Payment
  signupBusiness(requestBody: BusinessInput) : ID
  acceptBusinessDonation(donation: BusinessDonationInput) : Payment
  completePayment(input: PaymentResultInput): PaymentResult
  saveProfile(requestBody: ProfileInput): Profile
  generateResetPasswordToken(email: String): Result
  resetPassword(email: String, password: String, token: String): Result
  login(email: String, password: String): Result
}

scalar Long
scalar Url

type Metrics {
  fellowMetrics: FellowMetrics
  businessMetrics: BusinessMetrics
  donationMetrics: DonationMetrics
}

type FellowMetrics {
  signups: Long
  collaborators: Long
  betaTesters: Long
  referralPartners: Long
}

type BusinessMetrics {
  signups: Long
  betaTesters: Long
}

type DonationMetrics {
  totalDonations: String
  fellowDonations: String
  businessDonations: String
}

input FellowInput {
  name: String
  email: String
  betaTester: Boolean
  collaborator: Boolean
  message: String
  referralPartner: Boolean
  referralCode: String
}

input FellowDonationInput {
  name: String
  amount: String
  email: String
}

type Result {
  success: Boolean
  message: String
}

input BusinessInput {
  business: String
  email: String
  earlySignup: Boolean
  betaTester: Boolean
}

input BusinessDonationInput {
  businessName: String
  contactName: String
  email: String
  amount: String
  referral: String
}

type Payment {
  id: ID
  checkoutToken: String
  status: String
}

input PaymentResultInput {
  hash: String
  data: TransactionDataInput
  paymentId: ID
}

input TransactionDataInput {
  transactionId: String
  dateCreated: String
  cardBatchId: String
  status: String
  type: String
  amount: String
  currency: String
  avsResponse: String
  cvvResponse: String
  approvalCode: String
  cardToken: String
  cardNumber: String
  cardHolderName: String
  customerCode: String
  invoiceNumber: String
  warning: String
}

# Assuming you have a type to represent the result of the transaction
type PaymentResult {
  # Define fields for the result
  success: Boolean
  message: String
  # Add any other fields you need for the result
  payment: Payment
}

input ProfileInput {
  firstName: String
  lastName: String
  email: String
  password: String
  smallBio: String
  location: String
  skills: [String]
  jobTitles: [String]
  experiences: [ExperienceInput]
  education: [EducationInput]
  awardsAndHonors: [AwardOrHonorInput]
  experienceLevels: [ExperienceLevelInput]
  accomplishments: [AccomplishmentInput]
# Links:: String
  personalWebsite: Url
  portfolioWebsite: Url
  socialMediaLinks: [Url]
  otherLink: Url
# personalDetails:: String
  passionateAbout: String
  lookingFor: String
  quirksAndHobbies: String
  documents: String
  favoriteBookOrQuote: String
  moreAboutYou: String
# subscriptionDetails: SubscriptionDetails
    # Current Subscription Amount: String
    # Date of Subscription Renewal?: String
# Application List: String
    # Daily Application Counter: String
# Messaging Information?: String

}

input ExperienceInput {
  title: String
  company: String
  yearOrYears: String
  details: String
}

input EducationInput {
  degreeOrCertificate: String
  schoolName: String
  fieldOfStudy: String
}

input AwardOrHonorInput {
  awardOrHonor: String
  givenBy: String
  criteria: String
}

input ExperienceLevelInput {
  experienceLevel: String
  skill: String
  numberOfYears: String
}

input AccomplishmentInput {
  accomplishment: String
  details: String
}

type Profile {
  firstName: String
  lastName: String
  email: String
  password: String
  smallBio: String
  location: String
  skills: [String]
  jobTitles: [String]
  experiences: [Experience]
  education: [Education]
  awardsAndHonors: [AwardOrHonor]
  experienceLevels: [ExperienceLevel]
  accomplishments: [Accomplishment]
# Links:: String
  personalWebsite: Url
  portfolioWebsite: Url
  socialMediaLinks: [Url]
  otherLink: Url
# personalDetails:: String
  passionateAbout: String
  lookingFor: String
  quirksAndHobbies: String
  documents: String
  favoriteBookOrQuote: String
  moreAboutYou: String
# subscriptionDetails: SubscriptionDetails
    # Current Subscription Amount: String
    # Date of Subscription Renewal?: String
# Application List: String
    # Daily Application Counter: String
# Messaging Information?: String

}

type Experience {
  title: String
  company: String
  yearOrYears: String
  details: String
}

type Education {
  degreeOrCertificate: String
  schoolName: String
  fieldOfStudy: String
}

type AwardOrHonor {
  awardOrHonor: String
  givenBy: String
  criteria: String
}

type ExperienceLevel {
  experienceLevel: String
  skill: String
  numberOfYears: String
}

type Accomplishment {
  accomplishment: String
  details: String
}
