type Query {
  helloWorld: String
  jobs: [JobListing!]!
  fellowProfile: Profile
}

type Mutation {
  signupFellow(
      email: String!,
      password: String!,
      name: String!,
      isBetaTester: Boolean,
      isCollaborator: Boolean,
      message: String,
      referralCode: String,
      isReferralPartner: Boolean
    ): ID!

  signupBusiness(
      email: String!,
      password: String!,
      name: String!,
      isBetaTester: Boolean!,
      contactName: String!,
      isEarlySignup: Boolean,
      referral: String!
    ): ID!

  acceptFellowDonation(
      email: String!,
      password: String!,
      name: String!,
      isBetaTester: Boolean!,
      isCollaborator: Boolean!,
      message: String!,
      referralCode: String,
      isReferralPartner: Boolean!
      amount: String!,
      currency: String!,
      paymentType: String!
    ): ClientCheckoutData!

  acceptBusinessDonation(
      email: String!,
      password: String!,
      name: String!,
      isBetaTester: Boolean!,
      contactName: String!,
      isEarlySignup: Boolean,
      referral: String!,
      amount: String!,
      currency: String!,
      paymentType: String!
    ): ClientCheckoutData!

  generateResetPasswordToken(email: String!): String!

  resetPassword(email: String!, password: String!, token: String!): Boolean!

  login(email: String!, password: String!): [String!]!

  saveFellowProfilePage1(
    smallBio: String!,
    country: String!,
    location: String!,
    skills: [String!]!,
    jobTitles: [String!]!,
    languages: [String!]!
    ): Boolean!

  saveFellowProfilePage2(
    experience: [Experience!]!,
    education: [Education!]!
    ): Boolean!

  createJobListing(
    jobTitle: String!,
    positionType: String!
  ): ID!

  addJobListingDetailsStep1(
    id: ID!,
    positionSummary: String!,
    nonNegParams: [String!]!
    ): ID!

  applyToJob(
    jobId: ID!,
    message: String!
  ): ID!

  keepNotes(
    jobApplicationId: ID!,
    notes: [String!]!
  ): [ID!]!

  scheduleAppointments(
    jobApplicationId: ID!,
    appointments: [JobInterviewAppointmentInput!]!
  ): [ID!]!

  saveJobListing(
    jobId: ID!
  ): String
}

scalar Long
scalar Url
scalar DateTime

directive @Pattern(regexp: String!) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

type ClientCheckoutData {
  id: ID!,
  status: PaymentStatus!,
  checkoutToken: String!
}

enum PaymentStatus {
  APPROVED
  PENDING
}

input Experience {
  id: ID
  title: String!
  companyName: String!
  yearDetails: String!
  details: String!
}

input Education {
  id: ID
  degree: String!
  school: String!
  fieldOfStudy: String!
}

type JobListing {
  id: ID
}

input JobInterviewAppointmentInput {
  interviewDateAndTime: DateTime!
  # interviewDateAndTime: DateTime! @Pattern(regexp: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$")
  note: String
}

type Profile {
  smallBio: String!,
  country: String!,
  location: String!,
  skills: [String!]!,
  jobTitles: [String!]!,
  languages: [String!]!
}
